spring:
  application:
    name: spring-security-basic-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: 12345@qweA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9093

